# Generated by Django 5.2.17 on 2026-08-10 11:05
# Hand-edited: added delete_blank_email_users (see docs/DECISIONS.md § Stage 3
# decisions). The email-unique AlterField was split out into 0003 — Postgres
# refuses ALTER TABLE ... ADD CONSTRAINT UNIQUE in the same transaction as a
# preceding DELETE on the same table (the DELETE's FK/RI triggers are still
# pending), and each migration file is its own transaction, so splitting
# lets the delete commit before the uniqueness change runs.

from django.db import migrations, models

import accounts.models


def delete_blank_email_users(apps, schema_editor):
    """
    A pre-Stage-3 superuser row exists with email='' (created back when
    `username` was the login field). It has no email, so it can't verify,
    reset a password, or be linked to anyone — and once `email` is unique
    below, a second such row would collide with it. Deleted here rather than
    left as a permanently-unusable row that becomes a constraint violation
    waiting to happen; recreate a superuser with a real email afterward.
    """
    User = apps.get_model("accounts", "User")
    User.objects.filter(email="").delete()


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", accounts.models.UserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name="user",
            name="username",
        ),
        migrations.AddField(
            model_name="user",
            name="email_verified_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RunPython(
            delete_blank_email_users,
            # Deleted rows can't be un-deleted — there is no meaningful
            # reverse for a data-loss operation, so this is a deliberate
            # no-op rather than an attempt to reconstruct deleted rows.
            reverse_code=migrations.RunPython.noop,
        ),
    ]
