# Generated by Django 5.2.17 on 2026-08-09 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Salon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("slug", models.SlugField(unique=True)),
                ("timezone", models.CharField(default="Europe/Kyiv", max_length=63)),
                (
                    "deposit_percentage",
                    models.DecimalField(decimal_places=2, default=20, max_digits=5),
                ),
                ("min_lead_time_hours", models.PositiveIntegerField(default=3)),
                ("max_advance_days", models.PositiveIntegerField(default=60)),
                ("slot_granularity_minutes", models.PositiveIntegerField(default=15)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
    ]
