# Generated by Django 5.2.17 on 2026-08-10 10:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="salon",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
