# Generated by Django 5.2.17 on 2026-08-19 13:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenants", "0002_salon_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="salon",
            name="currency",
            field=models.CharField(
                default="UAH",
                max_length=3,
                validators=[django.core.validators.RegexValidator("^[A-Z]{3}$")],
            ),
            preserve_default=False,
        ),
    ]
