# Generated by Django 5.2.17 on 2026-08-19 14:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenants", "0003_salon_currency"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="salon",
            constraint=models.CheckConstraint(
                condition=models.Q(("currency__regex", "^[A-Z]{3}$")),
                name="salon_currency_iso_4217",
            ),
        ),
    ]
