# Generated by Django 5.2.17 on 2026-08-11 09:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0001_initial"),
        ("tenants", "0002_salon_is_active"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="service",
            options={"ordering": ["ordering", "name"]},
        ),
        migrations.AddField(
            model_name="service",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="service",
            name="ordering",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="servicecategory",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddConstraint(
            model_name="service",
            constraint=models.UniqueConstraint(
                fields=("salon", "name"), name="service_salon_name_uniq"
            ),
        ),
    ]
