# Generated by Django 5.2.17 on 2026-08-09 12:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("booking", "0001_initial"),
        ("tenants", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "channel",
                    models.CharField(
                        choices=[("email", "Email"), ("telegram", "Telegram")], max_length=16
                    ),
                ),
                (
                    "trigger_type",
                    models.CharField(
                        choices=[
                            ("booking_confirmed", "Booking confirmed"),
                            ("booking_cancelled", "Booking cancelled"),
                            ("appointment_reminder", "Appointment reminder"),
                            ("payment_succeeded", "Payment succeeded"),
                            ("payment_failed", "Payment failed"),
                            ("review_request", "Review request"),
                            ("email_verification", "Email verification"),
                        ],
                        max_length=32,
                    ),
                ),
                ("dedup_key", models.CharField(max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[("pending", "Pending"), ("sent", "Sent")],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                (
                    "appointment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="booking.appointment",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="accounts.customer",
                    ),
                ),
                (
                    "salon",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="tenants.salon",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("trigger_type", "channel", "dedup_key"),
                        name="notification_trigger_channel_dedup_uniq",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("customer__isnull", False), ("user__isnull", True)),
                            models.Q(("customer__isnull", True), ("user__isnull", False)),
                            _connector="OR",
                        ),
                        name="notification_exactly_one_recipient",
                    ),
                ],
            },
        ),
    ]
