# Generated by Django 5.2.17 on 2026-08-10 08:07

import django.db.models.deletion
from django.db import migrations, models

from core.db import composite_tenant_fk


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("catalog", "0001_initial"),
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Specialist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("bio", models.TextField(blank=True)),
                (
                    "salon",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="tenants.salon",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SpecialistService",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "salon",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="tenants.salon",
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="catalog.service"
                    ),
                ),
                (
                    "specialist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="specialists.specialist"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="specialist",
            name="services",
            field=models.ManyToManyField(
                related_name="specialists",
                through="specialists.SpecialistService",
                to="catalog.service",
            ),
        ),
        migrations.CreateModel(
            name="TimeOff",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("start_datetime", models.DateTimeField()),
                ("end_datetime", models.DateTimeField()),
                ("reason", models.CharField(blank=True, max_length=255)),
                (
                    "salon",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="tenants.salon",
                    ),
                ),
                (
                    "specialist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="time_off",
                        to="specialists.specialist",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="WorkingHours",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "day_of_week",
                    models.IntegerField(
                        choices=[
                            (0, "Monday"),
                            (1, "Tuesday"),
                            (2, "Wednesday"),
                            (3, "Thursday"),
                            (4, "Friday"),
                            (5, "Saturday"),
                            (6, "Sunday"),
                        ]
                    ),
                ),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                (
                    "salon",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="tenants.salon",
                    ),
                ),
                (
                    "specialist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="working_hours",
                        to="specialists.specialist",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddConstraint(
            model_name="specialistservice",
            constraint=models.UniqueConstraint(
                fields=("id", "salon"), name="specialists_specialistservice_id_salon_uniq"
            ),
        ),
        migrations.AddConstraint(
            model_name="specialistservice",
            constraint=models.UniqueConstraint(
                fields=("specialist", "service"), name="specialistservice_specialist_service_uniq"
            ),
        ),
        migrations.AddConstraint(
            model_name="specialist",
            constraint=models.UniqueConstraint(
                fields=("id", "salon"), name="specialists_specialist_id_salon_uniq"
            ),
        ),
        migrations.AddConstraint(
            model_name="timeoff",
            constraint=models.UniqueConstraint(
                fields=("id", "salon"), name="specialists_timeoff_id_salon_uniq"
            ),
        ),
        migrations.AddConstraint(
            model_name="timeoff",
            constraint=models.CheckConstraint(
                condition=models.Q(("start_datetime__lt", models.F("end_datetime"))),
                name="timeoff_start_before_end",
            ),
        ),
        migrations.AddConstraint(
            model_name="workinghours",
            constraint=models.UniqueConstraint(
                fields=("id", "salon"), name="specialists_workinghours_id_salon_uniq"
            ),
        ),
        migrations.AddConstraint(
            model_name="workinghours",
            constraint=models.CheckConstraint(
                condition=models.Q(("start_time__lt", models.F("end_time"))),
                name="workinghours_start_before_end",
            ),
        ),
        composite_tenant_fk(
            child_table="specialists_workinghours",
            fk_column="specialist_id",
            parent_table="specialists_specialist",
            constraint_name="specialists_workinghours_specialist_composite_fk",
        ),
        composite_tenant_fk(
            child_table="specialists_timeoff",
            fk_column="specialist_id",
            parent_table="specialists_specialist",
            constraint_name="specialists_timeoff_specialist_composite_fk",
        ),
        composite_tenant_fk(
            child_table="specialists_specialistservice",
            fk_column="specialist_id",
            parent_table="specialists_specialist",
            constraint_name="specialists_specialistservice_specialist_composite_fk",
        ),
        composite_tenant_fk(
            child_table="specialists_specialistservice",
            fk_column="service_id",
            parent_table="catalog_service",
            constraint_name="specialists_specialistservice_service_composite_fk",
        ),
    ]
