# Generated by Django 5.2.17 on 2026-08-11 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("specialists", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="specialist",
            options={"ordering": ["name", "id"]},
        ),
        migrations.AddField(
            model_name="specialist",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
