# Generated by Django 5.2.17 on 2026-08-16 09:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("specialists", "0002_alter_specialist_options_specialist_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="specialist",
            name="photo",
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
