# Generated by Django 5.2.17 on 2026-08-10 08:07

import django.db.models.deletion
from django.db import migrations, models

from core.db import composite_tenant_fk


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("booking", "0001_initial"),
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("rating", models.PositiveSmallIntegerField()),
                ("text", models.TextField(blank=True)),
                ("hidden_at", models.DateTimeField(blank=True, null=True)),
                (
                    "appointment",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="review",
                        to="booking.appointment",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reviews",
                        to="accounts.customer",
                    ),
                ),
                (
                    "salon",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="tenants.salon",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "constraints": [
                    models.UniqueConstraint(
                        fields=("id", "salon"), name="reviews_review_id_salon_uniq"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("rating__gte", 1), ("rating__lte", 5)),
                        name="review_rating_between_1_and_5",
                    ),
                ],
            },
        ),
        composite_tenant_fk(
            child_table="reviews_review",
            fk_column="appointment_id",
            parent_table="booking_appointment",
            constraint_name="reviews_review_appointment_composite_fk",
        ),
        composite_tenant_fk(
            child_table="reviews_review",
            fk_column="customer_id",
            parent_table="accounts_customer",
            constraint_name="reviews_review_customer_composite_fk",
        ),
    ]
