# Generated by Django 5.2.17 on 2026-08-19 13:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="currency",
            field=models.CharField(
                default="UAH",
                max_length=3,
                validators=[django.core.validators.RegexValidator("^[A-Z]{3}$")],
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="payment",
            name="flagged_for_review",
            field=models.BooleanField(default=False),
        ),
    ]
