# Generated by Django 5.2.17 on 2026-08-19 14:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("booking", "0003_alter_appointment_hold_expires_at"),
        ("payments", "0002_payment_currency_payment_flagged_for_review"),
        ("tenants", "0004_salon_salon_currency_iso_4217"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="payment",
            constraint=models.CheckConstraint(
                condition=models.Q(("currency__regex", "^[A-Z]{3}$")),
                name="payment_currency_iso_4217",
            ),
        ),
    ]
