# Generated by Django 5.2.17 on 2026-08-09 12:37

import django.contrib.postgres.constraints
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("catalog", "0001_initial"),
        ("specialists", "0001_initial"),
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Appointment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("start_datetime", models.DateTimeField()),
                ("end_datetime", models.DateTimeField()),
                ("blocked_until", models.DateTimeField()),
                ("service_price_at_booking", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "deposit_percentage_at_booking",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                ("hold_expires_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending_payment", "Pending payment"),
                            ("confirmed", "Confirmed"),
                            ("cancelled", "Cancelled"),
                            ("expired", "Expired"),
                            ("completed", "Completed"),
                            ("no_show", "No-show"),
                        ],
                        default="pending_payment",
                        max_length=32,
                    ),
                ),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                (
                    "cancelled_by",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("customer", "Customer"),
                            ("guest", "Guest"),
                            ("staff", "Staff"),
                            ("system", "System"),
                        ],
                        max_length=16,
                        null=True,
                    ),
                ),
                ("cancellation_reason", models.TextField(blank=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="appointments",
                        to="accounts.customer",
                    ),
                ),
                (
                    "salon",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="tenants.salon",
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="appointments",
                        to="catalog.service",
                    ),
                ),
                (
                    "specialist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="appointments",
                        to="specialists.specialist",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["specialist", "start_datetime"], name="appt_specialist_start_idx"
                    ),
                    models.Index(fields=["salon", "status"], name="appointment_salon_status_idx"),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("start_datetime__lt", models.F("end_datetime"))),
                        name="appointment_start_before_end",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("end_datetime__lte", models.F("blocked_until"))),
                        name="appointment_end_before_or_equal_blocked_until",
                    ),
                    django.contrib.postgres.constraints.ExclusionConstraint(
                        condition=models.Q(("status__in", ["pending_payment", "confirmed"])),
                        expressions=[
                            ("specialist", "="),
                            (
                                models.Func(
                                    "start_datetime", "blocked_until", function="TSTZRANGE"
                                ),
                                "&&",
                            ),
                        ],
                        name="appointment_no_overlapping_active_bookings",
                    ),
                ],
            },
        ),
    ]
