# Generated by Django 5.2.17 on 2026-08-10 13:28

import django.db.models.deletion
from django.db import migrations, models

from core.db import composite_tenant_fk


class Migration(migrations.Migration):
    dependencies = [
        ("booking", "0001_initial"),
        ("tenants", "0002_salon_is_active"),
    ]

    operations = [
        migrations.CreateModel(
            name="GuestAccessToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("token_hash", models.CharField(max_length=64, unique=True)),
                ("expires_at", models.DateTimeField()),
                ("cancelled_via_token_at", models.DateTimeField(blank=True, null=True)),
                (
                    "appointment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="guest_access_tokens",
                        to="booking.appointment",
                    ),
                ),
                (
                    "salon",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="tenants.salon",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "constraints": [
                    models.UniqueConstraint(
                        fields=("id", "salon"), name="booking_guestaccesstoken_id_salon_uniq"
                    )
                ],
            },
        ),
        composite_tenant_fk(
            child_table="booking_guestaccesstoken",
            fk_column="appointment_id",
            parent_table="booking_appointment",
            constraint_name="booking_guestaccesstoken_appointment_composite_fk",
        ),
    ]
