# Generated by Django 5.2.17 on 2026-08-17 09:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("booking", "0002_guestaccesstoken"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointment",
            name="hold_expires_at",
            field=models.DateTimeField(),
        ),
    ]
